config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  root to: 'articles#index'

  resources :articles do
    resources :comments
  end

  resources :tags
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :taggings#, dependent: :destroy
  has_many :tags, through: :taggings
  has_attached_file :image, styles: { medium: "300x300", thumb: "100x100" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

end

app/models/author.rb
class Author < ActiveRecord::Base
  validates :username, :uniqueness => { :case_sensitive => false }
  validates :username, presence: true, length: { maximum: 30 }
  validates :email, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings#, dependent: :destroy
  has_many :articles, through: :taggings

  def to_s
    name
  end

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  before_action :authenticate_author!, except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save

    flash.notice = "Article '#{@article.title}' Created!"

    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    flash.notice = "Article '#{@article.title}' Deleted!"

    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article '#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_author!, except: [:create]

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]

    @comment.save

    redirect_to article_path(@comment.article)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_author!, only: [:destroy]

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    flash.notice = "Tag '#{@tag.name}' Deleted!"

    redirect_to tags_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.slim
div
  h4
    ' Comment by
    = comment.author_name
  p class="comment"
    = comment.body
  p
    ' Posted
    = distance_of_time_in_words(comment.article.created_at, comment.created_at)
    '  later

app/views/articles/_form.html.slim
= form_for(@article, html: {multipart: true}) do |f|
  ul
  - @article.errors.full_messages.each do |error|
    li = error

  p
    = f.label :title
    = f.text_field :title
  br
  p
    = f.label :body
    = f.text_area :body
  br
  p
    = f.label :tag_list
  	= f.text_field :tag_list
  br
  p
    - if @article.image.exists?
      = image_tag @article.image.url(:thumb)
      br
    = f.label :image, "Attach an Image"
    = f.file_field :image
  br
  p = f.submit

app/views/articles/edit.html.slim
h1 Edit an Article

= render partial: 'form'

app/views/articles/index.html.slim
h1 All Articles

ul id="articles"
  - @articles.each do |article|
    li = link_to article.title, article_path(article)

- if author_signed_in?
  = link_to "Create a new Article", new_article_path,  class: "new_article"

app/views/articles/new.html.slim
h1 Create a New Article

= render partial: 'form'

app/views/articles/show.html.slim
h1 = @article.title

p Tags:
- @article.tags.each do |tag|
  = link_to tag.name, tag_path(tag)
br

p
  - if @article.image.exists?
    br
    = image_tag @article.image.url(:medium)
br
p = @article.body

h3
  ' Comments
  = @article.comments.size
  = render partial: 'articles/comment', collection: @article.comments

= render partial: 'comments/form'

= link_to "<< Back to Articles List", articles_path
br
- if author_signed_in?
  = link_to "Edit", edit_article_path(@article)
  br
  = link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"}

app/views/comments/_form.html.slim
h3 Post a Comment

= form_for [ @article, @comment ] do |f|
  p
    = f.label :author_name, 'Your Name'
    = f.text_field :author_name
  br
  p
    = f.label :body, 'Your Comment'
    = f.text_area :body
  br
  p = f.submit 'Submit'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="flash">
    <%= flash.notice %>
  </p>
  <div id="content">
    <%= yield %>
    <hr>
    <h6>
      <% if author_signed_in? %>
        <%= "Logged in as #{current_author.username}" %>
        <%= link_to "Sign Out", destroy_author_session_path, :method => :delete %>
      <% else %>
        Already a member? <%= link_to "Sign In", new_author_session_path %>
        <br>
        Not a member? <%= link_to "Sign Up", new_author_registration_path %>
      <% end %>
    </h6>
  </div>
</body>
</html>

app/views/tags/index.html.slim
h1 All Tags

ul id="tags"
  - @tags.each do |tag|
    li = link_to tag.name, tag_path(tag)

app/views/tags/show.html.slim
h1
  ' Articles Tagged with
  = @tag.name

ul
  - @tag.articles.each do |article|
    li = link_to article.title, article_path(article)
br
= link_to "<< Back to Tags List", tags_path
br
- if author_signed_in?
  = link_to "Delete", tag_path(@tag), method: :delete, data: {confirm: "Really delete the tag?"}